### ISSUE TITLE
Provide some guidance on dependencies and known good platforms

### ISSUE THREAD

**Issue by firthmj** [GlitchedPolygons/l8w8jwtgui#1]
It would be useful to have some guidance on which Linux distribution(s) this has been tested working on, and what version of QT etc is needed to get this to build correctly.

For example, it seems it needs QT 5.15, but it also seems to not completely cleanly build on Debian 11 (see other issue) which has 5.15.2.

Also, adding a note somewhere that the CMake instantiation for l8w8jwtgui has to have the "-DL8W8JWT_ENABLE_EDDSA=On" parameter for the sub-library l8w8jwt specified or the build will fail would help people.

**Comment by GlitchedPolygons** [comment]
Hi there @firthmj ,

Good idea! This is all still very fresh, so I'm sure there's many things missing in the README.md :)

I tested (and released) this on x64 Kubuntu 20 (LTS) with Qt 6.2.2 using the Qt Creator.

The Linux package in the [Releases page](https://github.com/GlitchedPolygons/l8w8jwtgui/releases/tag/1.0.1) contains all the dependencies bundled for making it work on (K)ubuntu.

I actually don't know how the process is easiest/least painful for people who want to build from source on other distros using the CLI. Maybe you can help with that? I'm open for pull requests and I'd be gladly reviewing them 😃

**Comment by firthmj** [comment]
I'm probably slightly unusual in that I use cmake from the CLI quite a lot for other things, so just having some guidance on parameters to pass to cmake would be useful.

But for any project, having a "stake in the ground" Linux distribution where it is known to build and work is very useful, so knowing it has been tested on Ubuntu 20 is very helpful.

I think I will submit a PR to get it to build and run on Debian 11 (which has QT 5.15, as I said before) - it isn't a big delta.
